filetype: 'ignore'

detect:
  filename: '.*ignore$'

rules:
  - statement: '.*$'         # files
  - constant.string: '.*/$'  # diretories
  - error: "^\\!.*"          # negated

  - special: '/'
  - identifier: '!|\*|\[.*]'

  - comment: '#.*$'
